
  window:
    padding:
      x: 15
      y: 15

# Background opacity
  opacity: 1.0

  scrolling:
    history: 100000
    multiplier: 20

# Font configuration
  font:
    normal:
      family: Source Code Pro Semibold 
      style: Regular
# Bold font face
    bold:
      family: Source Code Pro Semibold
      style: Bold
# Italic font face
    italic:
      family: Source Code Pro Semibold
      style: Italic

# Bold italic font face
    bold_italic:
      family: Source Code Pro Semibold
      style: Bold Italic
    size: 14.0

# If `true`, bold text is drawn using the bright color variants.
  draw_bold_text_with_bright_colors: true

# Colors (Tomorrow Night)
  colors:
    primary:
     background: '#1d1f21'
     foreground: '#C6EFFA'
    #dim_foreground: '#828482'
    #bright_foreground: '#eaeaea'

  # Normal colors
  #NOrmal:
  #  black:   '#1d1f21'
  #  red:     '#cc6666'
  #  green:   '#b5bd68'
  #  yellow:  '#f0c674'
  #  blue:    '#81a2be'
  #  magenta: '#b294bb'
  #  cyan:    '#8abeb7'
  #  white:   '#c5c8c6'

  # Bright colors
  #bright:
  #  black:   '#666666'
  #  red:     '#d54e53'
  #  green:   '#b9ca4a'
  #  yellow:  '#e7c547'
  #  blue:    '#7aa6da'
  #  magenta: '#c397d8'
  #  cyan:    '#70c0b1'
  #  white:   '#eaeaea'

  # Dim colors
  #
  # If the dim colors are not set, they will be calculated automatically based
  # on the `normal` colors.
  #dim:
  #  black:   '#131415'
  #  red:     '#864343'
  #  green:   '#777c44'
  #  yellow:  '#9e824c'
  #  blue:    '#556a7d'
  #  magenta: '#75617b'
  #  cyan:    '#5b7d78'
  #  white:   '#828482'

  cursor:
    style: 
      blinking: On

  key_bindings:
    - { key: Minus,  mods: Control,         action: DecreaseFontSize }
    - { key: Plus,   mods: Control,         action: IncreaseFontSize }
    - { key: V,      mods: Control,         action: Paste            }
    - { key: X,      mods: Control,         action: Copy             }
