[colors]
draw_bold_text_with_bright_colors = true

[colors.primary]
background = "#1d1f21"
foreground = "#C6EFFA"

[cursor.style]
blinking = "On"

[font]
size = 15.0

[font.bold]
family = "Source Code Pro Semibold"
style = "Bold"

[font.bold_italic]
family = "Source Code Pro Semibold"
style = "Bold Italic"

[font.italic]
family = "Source Code Pro Semibold"
style = "Italic"

[font.normal]
family = "Source Code Pro Semibold"
style = "Regular"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Minus"
mods = "Control"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Plus"
mods = "Control"

[scrolling]
history = 100000
multiplier = 10

[window.padding]
x = 15
y = 15
